; 10 SYS (4096)
*=$0801
          BYTE           $0E, $08, $0A, $00, $9E, $20, $28,  $34, $30, $39, $36, $29, $00, $00, $00
*=$1000
;helpful labels
CLEAR     = $E544
GETIN     = $FFE4
CHROUT    = $FFD2
SCNKEY    = $FF9F
PLOT      = $E50A
STROUT    = $AB1E
PLAYER    = #88
PLAYER_ROW_I = $02
PLAYER_COL_I = $03
PLAYERPD  = $00         ; player prev dir (1 up, 2 left, 3 right, 4 down)
rowL = $05
rowH = $06
GAMESPEED = #100
GHOSTX    = #01
GHOSTY    = #01
SCRN_START = $0400
;SCRN_OFFSET = $03
WALL      = #102

start
          lda #00
          sta PLAYERPD
          lda #13
          sta PLAYER_COL_I
          lda #11
          sta PLAYER_ROW_I
          jsr drwscrn
          clc
DRWPLYR   
          ldx PLAYER_ROW_I
          lda ScreenRowTableDataL,x
          sta rowL
          lda ScreenRowTableDataH,x
          sta rowH
          ldy PLAYER_COL_I
          lda PLAYER
          sta (rowL),Y
SCAN      
          JSR SCNKEY    ; get key
          JSR GETIN     ; put key in A
          CMP #87
          BEQ JMP_MVPLYR_UP
          CMP #83
          BEQ JMP_MVPLYR_DN
          CMP #65
          BEQ JMP_MVPLYR_LF
          CMP #68
          BEQ JMP_MVPLYR_RT
          CMP #81       ; end if Q clicked
          BEQ END
          LDA PLAYERPD
          CMP #01
          BEQ JMP_MVPLYR_UP
          CMP #02
          BEQ JMP_MVPLYR_LF
          CMP #03
          BEQ JMP_MVPLYR_RT
          CMP #04
          BEQ JMP_MVPLYR_DN
          JMP SCAN
JMP_MVPLYR_UP
          JMP MVPLYR_UP
JMP_MVPLYR_DN
          JMP MVPLYR_DN
JMP_MVPLYR_LF
          JMP MVPLYR_LF
JMP_MVPLYR_RT
          JMP MVPLYR_RT
END       
          JSR CLEAR
          RTS

CLRPLYR   
          ldx PLAYER_ROW_I
          lda ScreenRowTableDataL,x
          sta rowL
          lda ScreenRowTableDataH,x
          sta rowH
          ldy PLAYER_COL_I
          lda #32
          sta (rowL),Y
          rts
DELAY
          LDA #$00
          STA $BB
          STA $BC 
DLY
          INC $BB
          BNE DLY 
          INC $BC
          LDA $BC
          CMP GAMESPEED
          BNE DLY 
          RTS     
MVPLYR_UP
          ; OK move up ?
          ldx PLAYER_ROW_I
          dex
          lda ScreenRowTableDataL,x
          sta rowL
          lda ScreenRowTableDataH,x
          sta rowH
          ldy PLAYER_COL_I
          lda WALL
          cmp (rowL),Y
          bne MVPLYR_UP_OK               
          JMP SCAN
MVPLYR_UP_OK
          jsr DELAY
          jsr CLRPLYR
          lda PLAYER_ROW_I
          sec
          sbc #1
          sta PLAYER_ROW_I
          lda #01
          sta PLAYERPD
          JMP DRWPLYR
MVPLYR_DN
          ; OK move down ?
          ldx PLAYER_ROW_I
          inx
          lda ScreenRowTableDataL,x
          sta rowL
          lda ScreenRowTableDataH,x
          sta rowH
          ldy PLAYER_COL_I
          lda WALL
          cmp (rowL),Y
          bne MVPLYR_DN_OK               
          JMP SCAN
MVPLYR_DN_OK
          jsr DELAY
          jsr CLRPLYR
          lda PLAYER_ROW_I
          clc
          adc #1
          sta PLAYER_ROW_I
          lda #04
          sta PLAYERPD
          JMP DRWPLYR
MVPLYR_LF
          ; OK move left ?
          ldx PLAYER_ROW_I
          lda ScreenRowTableDataL,x
          sta rowL
          lda ScreenRowTableDataH,x
          sta rowH
          ldy PLAYER_COL_I
          dey
          lda WALL
          cmp (rowL),Y
          bne MVPLYR_LF_OK               
          JMP SCAN
MVPLYR_LF_OK
          jsr DELAY
          jsr CLRPLYR
          lda PLAYER_COL_I
          sec
          sbc #1
          sta PLAYER_COL_I
          lda #02
          sta PLAYERPD
          JMP DRWPLYR
MVPLYR_RT
          ; OK move right ?
          ldx PLAYER_ROW_I
          lda ScreenRowTableDataL,x
          sta rowL
          lda ScreenRowTableDataH,x
          sta rowH
          ldy PLAYER_COL_I
          iny
          lda WALL
          cmp (rowL),Y
          bne MVPLYR_RT_OK 
          JMP SCAN
MVPLYR_RT_OK
          jsr DELAY
          jsr CLRPLYR
          lda PLAYER_COL_I
          clc
          adc #1
          sta PLAYER_COL_I
          lda #03
          sta PLAYERPD
          JMP DRWPLYR
SCRNROWS  
          byte $0400
drwscrn
          lda            #5        ; color code for green
          sta            $0286     ; color code for the current cursor color
          jsr            CLEAR     ; clear screen
          lda            #102      ; char scrn display code for wall
          sta            $0400     ; $400-$7E7 video screen mem matrix
          lda            #102
          sta            $0401
          lda            #102
          sta            $0402
          lda            #102
          sta            $0403
          lda            #102
          sta            $0404
          lda            #102
          sta            $0405
          lda            #102
          sta            $0406
          lda            #102
          sta            $0407
          lda            #102
          sta            $0408
          lda            #102
          sta            $0409
          lda            #102
          sta            $040A
          lda            #102
          sta            $040B
          lda            #102
          sta            $040C
          lda            #102
          sta            $040D
          lda            #102
          sta            $040E
          lda            #102
          sta            $040F
          lda            #102
          sta            $0410
          lda            #102
          sta            $0411
          lda            #102
          sta            $0412
          lda            #102
          sta            $0413
          lda            #102
          sta            $0414
          lda            #102
          sta            $0415
          lda            #102
          sta            $0416
          lda            #102
          sta            $0417
          lda            #102
          sta            $0418
          lda            #102
          sta            $0419
          lda            #102
          sta            $041A
          lda            #102
          sta            $0428
          lda            #46
          sta            $0429
          lda            #46
          sta            $042A
          lda            #46
          sta            $042B
          lda            #46
          sta            $042C
          lda            #46
          sta            $042D
          lda            #46
          sta            $042E
          lda            #46
          sta            $042F
          lda            #46
          sta            $0430
          lda            #46
          sta            $0431
          lda            #46
          sta            $0432
          lda            #46
          sta            $0433
          lda            #46
          sta            $0434
          lda            #102
          sta            $0435
          lda            #46
          sta            $0436
          lda            #46
          sta            $0437
          lda            #46
          sta            $0438
          lda            #46
          sta            $0439
          lda            #46
          sta            $043A
          lda            #46
          sta            $043B
          lda            #46
          sta            $043C
          lda            #46
          sta            $043D
          lda            #46
          sta            $043E
          lda            #46
          sta            $043F
          lda            #46
          sta            $0440
          lda            #46
          sta            $0441
          lda            #102
          sta            $0442
          lda            #102
          sta            $0450
          lda            #46
          sta            $0451
          lda            #102
          sta            $0452
          lda            #102
          sta            $0453
          lda            #102
          sta            $0454
          lda            #102
          sta            $0455
          lda            #46
          sta            $0456
          lda            #102
          sta            $0457
          lda            #102
          sta            $0458
          lda            #102
          sta            $0459
          lda            #102
          sta            $045A
          lda            #102
          sta            $045B
          lda            #46
          sta            $045C
          lda            #102
          sta            $045D
          lda            #46
          sta            $045E
          lda            #102
          sta            $045F
          lda            #102
          sta            $0460
          lda            #102
          sta            $0461
          lda            #102
          sta            $0462
          lda            #102
          sta            $0463
          lda            #46
          sta            $0464
          lda            #102
          sta            $0465
          lda            #102
          sta            $0466
          lda            #102
          sta            $0467
          lda            #102
          sta            $0468
          lda            #46
          sta            $0469
          lda            #102
          sta            $046A
          lda            #102
          sta            $0478
          lda            #46
          sta            $0479
          lda            #102
          sta            $047A
          lda            #102
          sta            $047B
          lda            #102
          sta            $047C
          lda            #102
          sta            $047D
          lda            #46
          sta            $047E
          lda            #102
          sta            $047F
          lda            #102
          sta            $0480
          lda            #102
          sta            $0481
          lda            #102
          sta            $0482
          lda            #102
          sta            $0483
          lda            #46
          sta            $0484
          lda            #102
          sta            $0485
          lda            #46
          sta            $0486
          lda            #102
          sta            $0487
          lda            #102
          sta            $0488
          lda            #102
          sta            $0489
          lda            #102
          sta            $048A
          lda            #102
          sta            $048B
          lda            #46
          sta            $048C
          lda            #102
          sta            $048D
          lda            #102
          sta            $048E
          lda            #102
          sta            $048F
          lda            #102
          sta            $0490
          lda            #46
          sta            $0491
          lda            #102
          sta            $0492
          lda            #102
          sta            $04A0
          lda            #46
          sta            $04A1
          lda            #102
          sta            $04A2
          lda            #102
          sta            $04A3
          lda            #102
          sta            $04A4
          lda            #102
          sta            $04A5
          lda            #46
          sta            $04A6
          lda            #102
          sta            $04A7
          lda            #102
          sta            $04A8
          lda            #102
          sta            $04A9
          lda            #102
          sta            $04AA
          lda            #102
          sta            $04AB
          lda            #46
          sta            $04AC
          lda            #102
          sta            $04AD
          lda            #46
          sta            $04AE
          lda            #102
          sta            $04AF
          lda            #102
          sta            $04B0
          lda            #102
          sta            $04B1
          lda            #102
          sta            $04B2
          lda            #102
          sta            $04B3
          lda            #46
          sta            $04B4
          lda            #102
          sta            $04B5
          lda            #102
          sta            $04B6
          lda            #102
          sta            $04B7
          lda            #102
          sta            $04B8
          lda            #46
          sta            $04B9
          lda            #102
          sta            $04BA
          lda            #102
          sta            $04C8
          lda            #46
          sta            $04C9
          lda            #46
          sta            $04CA
          lda            #46
          sta            $04CB
          lda            #46
          sta            $04CC
          lda            #46
          sta            $04CD
          lda            #46
          sta            $04CE
          lda            #46
          sta            $04CF
          lda            #46
          sta            $04D0
          lda            #46
          sta            $04D1
          lda            #46
          sta            $04D2
          lda            #46
          sta            $04D3
          lda            #46
          sta            $04D4
          lda            #46
          sta            $04D5
          lda            #46
          sta            $04D6
          lda            #46
          sta            $04D7
          lda            #46
          sta            $04D8
          lda            #46
          sta            $04D9
          lda            #46
          sta            $04DA
          lda            #46
          sta            $04DB
          lda            #46
          sta            $04DC
          lda            #46
          sta            $04DD
          lda            #46
          sta            $04DE
          lda            #46
          sta            $04DF
          lda            #46
          sta            $04E0
          lda            #46
          sta            $04E1
          lda            #102
          sta            $04E2
          lda            #102
          sta            $04F0
          lda            #46
          sta            $04F1
          lda            #102
          sta            $04F2
          lda            #102
          sta            $04F3
          lda            #102
          sta            $04F4
          lda            #102
          sta            $04F5
          lda            #46
          sta            $04F6
          lda            #102
          sta            $04F7
          lda            #102
          sta            $04F8
          lda            #46
          sta            $04F9
          lda            #102
          sta            $04FA
          lda            #102
          sta            $04FB
          lda            #102
          sta            $04FC
          lda            #102
          sta            $04FD
          lda            #102
          sta            $04FE
          lda            #102
          sta            $04FF
          lda            #102
          sta            $0500
          lda            #46
          sta            $0501
          lda            #102
          sta            $0502
          lda            #102
          sta            $0503
          lda            #46
          sta            $0504
          lda            #102
          sta            $0505
          lda            #102
          sta            $0506
          lda            #102
          sta            $0507
          lda            #102
          sta            $0508
          lda            #46
          sta            $0509
          lda            #102
          sta            $050A
          lda            #102
          sta            $0518
          lda            #46
          sta            $0519
          lda            #102
          sta            $051A
          lda            #102
          sta            $051B
          lda            #102
          sta            $051C
          lda            #102
          sta            $051D
          lda            #46
          sta            $051E
          lda            #102
          sta            $051F
          lda            #102
          sta            $0520
          lda            #46
          sta            $0521
          lda            #102
          sta            $0522
          lda            #102
          sta            $0523
          lda            #102
          sta            $0524
          lda            #102
          sta            $0525
          lda            #102
          sta            $0526
          lda            #102
          sta            $0527
          lda            #102
          sta            $0528
          lda            #46
          sta            $0529
          lda            #102
          sta            $052A
          lda            #102
          sta            $052B
          lda            #46
          sta            $052C
          lda            #102
          sta            $052D
          lda            #102
          sta            $052E
          lda            #102
          sta            $052F
          lda            #102
          sta            $0530
          lda            #46
          sta            $0531
          lda            #102
          sta            $0532
          lda            #102
          sta            $0540
          lda            #46
          sta            $0541
          lda            #46
          sta            $0542
          lda            #46
          sta            $0543
          lda            #46
          sta            $0544
          lda            #46
          sta            $0545
          lda            #46
          sta            $0546
          lda            #102
          sta            $0547
          lda            #102
          sta            $0548
          lda            #46
          sta            $0549
          lda            #46
          sta            $054A
          lda            #46
          sta            $054B
          lda            #46
          sta            $054C
          lda            #102
          sta            $054D
          lda            #46
          sta            $054E
          lda            #46
          sta            $054F
          lda            #46
          sta            $0550
          lda            #46
          sta            $0551
          lda            #102
          sta            $0552
          lda            #102
          sta            $0553
          lda            #46
          sta            $0554
          lda            #46
          sta            $0555
          lda            #46
          sta            $0556
          lda            #46
          sta            $0557
          lda            #46
          sta            $0558
          lda            #46
          sta            $0559
          lda            #102
          sta            $055A
          lda            #102
          sta            $0568
          lda            #102
          sta            $0569
          lda            #102
          sta            $056A
          lda            #102
          sta            $056B
          lda            #102
          sta            $056C
          lda            #102
          sta            $056D
          lda            #46
          sta            $056E
          lda            #102
          sta            $056F
          lda            #102
          sta            $0570
          lda            #102
          sta            $0571
          lda            #102
          sta            $0572
          lda            #102
          sta            $0573
          lda            #46
          sta            $0574
          lda            #102
          sta            $0575
          lda            #46
          sta            $0576
          lda            #102
          sta            $0577
          lda            #102
          sta            $0578
          lda            #102
          sta            $0579
          lda            #102
          sta            $057A
          lda            #102
          sta            $057B
          lda            #46
          sta            $057C
          lda            #102
          sta            $057D
          lda            #102
          sta            $057E
          lda            #102
          sta            $057F
          lda            #102
          sta            $0580
          lda            #102
          sta            $0581
          lda            #102
          sta            $0582
          lda            #102
          sta            $0590
          lda            #102
          sta            $0591
          lda            #102
          sta            $0592
          lda            #102
          sta            $0593
          lda            #102
          sta            $0594
          lda            #102
          sta            $0595
          lda            #46
          sta            $0596
          lda            #102
          sta            $0597
          lda            #102
          sta            $0598
          lda            #102
          sta            $0599
          lda            #102
          sta            $059A
          lda            #102
          sta            $059B
          lda            #46
          sta            $059C
          lda            #102
          sta            $059D
          lda            #46
          sta            $059E
          lda            #102
          sta            $059F
          lda            #102
          sta            $05A0
          lda            #102
          sta            $05A1
          lda            #102
          sta            $05A2
          lda            #102
          sta            $05A3
          lda            #46
          sta            $05A4
          lda            #102
          sta            $05A5
          lda            #102
          sta            $05A6
          lda            #102
          sta            $05A7
          lda            #102
          sta            $05A8
          lda            #102
          sta            $05A9
          lda            #102
          sta            $05AA
          lda            #102
          sta            $05B8
          lda            #102
          sta            $05B9
          lda            #102
          sta            $05BA
          lda            #102
          sta            $05BB
          lda            #102
          sta            $05BC
          lda            #102
          sta            $05BD
          lda            #46
          sta            $05BE
          lda            #102
          sta            $05BF
          lda            #102
          sta            $05C0
          lda            #46
          sta            $05C1
          lda            #46
          sta            $05C2
          lda            #46
          sta            $05C3
          lda            #46
          sta            $05C4
          lda            #46
          sta            $05C5
          lda            #46
          sta            $05C6
          lda            #46
          sta            $05C7
          lda            #46
          sta            $05C8
          lda            #46
          sta            $05C9
          lda            #102
          sta            $05CA
          lda            #102
          sta            $05CB
          lda            #46
          sta            $05CC
          lda            #102
          sta            $05CD
          lda            #102
          sta            $05CE
          lda            #102
          sta            $05CF
          lda            #102
          sta            $05D0
          lda            #102
          sta            $05D1
          lda            #102
          sta            $05D2
          lda            #102
          sta            $05E0
          lda            #102
          sta            $05E1
          lda            #102
          sta            $05E2
          lda            #102
          sta            $05E3
          lda            #102
          sta            $05E4
          lda            #102
          sta            $05E5
          lda            #46
          sta            $05E6
          lda            #102
          sta            $05E7
          lda            #102
          sta            $05E8
          lda            #46
          sta            $05E9
          lda            #102
          sta            $05EA
          lda            #102
          sta            $05EB
          lda            #102
          sta            $05EC
          lda            #102
          sta            $05ED
          lda            #102
          sta            $05EE
          lda            #102
          sta            $05EF
          lda            #102
          sta            $05F0
          lda            #46
          sta            $05F1
          lda            #102
          sta            $05F2
          lda            #102
          sta            $05F3
          lda            #46
          sta            $05F4
          lda            #102
          sta            $05F5
          lda            #102
          sta            $05F6
          lda            #102
          sta            $05F7
          lda            #102
          sta            $05F8
          lda            #102
          sta            $05F9
          lda            #102
          sta            $05FA
          lda            #102
          sta            $0608
          lda            #102
          sta            $0609
          lda            #102
          sta            $060A
          lda            #102
          sta            $060B
          lda            #102
          sta            $060C
          lda            #102
          sta            $060D
          lda            #46
          sta            $060E
          lda            #102
          sta            $060F
          lda            #102
          sta            $0610
          lda            #46
          sta            $0611
          lda            #102
          sta            $0612
          lda            #102
          sta            $0613
          lda            #102
          sta            $0614
          lda            #102
          sta            $0615
          lda            #102
          sta            $0616
          lda            #102
          sta            $0617
          lda            #102
          sta            $0618
          lda            #46
          sta            $0619
          lda            #102
          sta            $061A
          lda            #102
          sta            $061B
          lda            #46
          sta            $061C
          lda            #102
          sta            $061D
          lda            #102
          sta            $061E
          lda            #102
          sta            $061F
          lda            #102
          sta            $0620
          lda            #102
          sta            $0621
          lda            #102
          sta            $0622
          lda            #102
          sta            $0630
          lda            #46
          sta            $0631
          lda            #46
          sta            $0632
          lda            #46
          sta            $0633
          lda            #46
          sta            $0634
          lda            #46
          sta            $0635
          lda            #46
          sta            $0636
          lda            #46
          sta            $0637
          lda            #46
          sta            $0638
          lda            #46
          sta            $0639
          lda            #46
          sta            $063A
          lda            #46
          sta            $063B
          lda            #46
          sta            $063C
          lda            #102
          sta            $063D
          lda            #46
          sta            $063E
          lda            #46
          sta            $063F
          lda            #46
          sta            $0640
          lda            #46
          sta            $0641
          lda            #46
          sta            $0642
          lda            #46
          sta            $0643
          lda            #46
          sta            $0644
          lda            #46
          sta            $0645
          lda            #46
          sta            $0646
          lda            #46
          sta            $0647
          lda            #46
          sta            $0648
          lda            #46
          sta            $0649
          lda            #102
          sta            $064A
          lda            #102
          sta            $0658
          lda            #46
          sta            $0659
          lda            #102
          sta            $065A
          lda            #102
          sta            $065B
          lda            #102
          sta            $065C
          lda            #102
          sta            $065D
          lda            #46
          sta            $065E
          lda            #102
          sta            $065F
          lda            #102
          sta            $0660
          lda            #102
          sta            $0661
          lda            #102
          sta            $0662
          lda            #102
          sta            $0663
          lda            #46
          sta            $0664
          lda            #102
          sta            $0665
          lda            #46
          sta            $0666
          lda            #102
          sta            $0667
          lda            #102
          sta            $0668
          lda            #102
          sta            $0669
          lda            #102
          sta            $066A
          lda            #102
          sta            $066B
          lda            #46
          sta            $066C
          lda            #102
          sta            $066D
          lda            #102
          sta            $066E
          lda            #102
          sta            $066F
          lda            #102
          sta            $0670
          lda            #46
          sta            $0671
          lda            #102
          sta            $0672
          lda            #102
          sta            $0680
          lda            #46
          sta            $0681
          lda            #102
          sta            $0682
          lda            #102
          sta            $0683
          lda            #102
          sta            $0684
          lda            #102
          sta            $0685
          lda            #46
          sta            $0686
          lda            #102
          sta            $0687
          lda            #102
          sta            $0688
          lda            #102
          sta            $0689
          lda            #102
          sta            $068A
          lda            #102
          sta            $068B
          lda            #46
          sta            $068C
          lda            #102
          sta            $068D
          lda            #46
          sta            $068E
          lda            #102
          sta            $068F
          lda            #102
          sta            $0690
          lda            #102
          sta            $0691
          lda            #102
          sta            $0692
          lda            #102
          sta            $0693
          lda            #46
          sta            $0694
          lda            #102
          sta            $0695
          lda            #102
          sta            $0696
          lda            #102
          sta            $0697
          lda            #102
          sta            $0698
          lda            #46
          sta            $0699
          lda            #102
          sta            $069A
          lda            #102
          sta            $06A8
          lda            #46
          sta            $06A9
          lda            #46
          sta            $06AA
          lda            #46
          sta            $06AB
          lda            #102
          sta            $06AC
          lda            #102
          sta            $06AD
          lda            #46
          sta            $06AE
          lda            #46
          sta            $06AF
          lda            #46
          sta            $06B0
          lda            #46
          sta            $06B1
          lda            #46
          sta            $06B2
          lda            #46
          sta            $06B3
          lda            #46
          sta            $06B4
          lda            #46
          sta            $06B5
          lda            #46
          sta            $06B6
          lda            #46
          sta            $06B7
          lda            #46
          sta            $06B8
          lda            #46
          sta            $06B9
          lda            #46
          sta            $06BA
          lda            #46
          sta            $06BB
          lda            #46
          sta            $06BC
          lda            #102
          sta            $06BD
          lda            #102
          sta            $06BE
          lda            #46
          sta            $06BF
          lda            #46
          sta            $06C0
          lda            #46
          sta            $06C1
          lda            #102
          sta            $06C2
          lda            #102
          sta            $06D0
          lda            #102
          sta            $06D1
          lda            #102
          sta            $06D2
          lda            #46
          sta            $06D3
          lda            #102
          sta            $06D4
          lda            #102
          sta            $06D5
          lda            #46
          sta            $06D6
          lda            #102
          sta            $06D7
          lda            #102
          sta            $06D8
          lda            #46
          sta            $06D9
          lda            #102
          sta            $06DA
          lda            #102
          sta            $06DB
          lda            #102
          sta            $06DC
          lda            #102
          sta            $06DD
          lda            #102
          sta            $06DE
          lda            #102
          sta            $06DF
          lda            #102
          sta            $06E0
          lda            #46
          sta            $06E1
          lda            #102
          sta            $06E2
          lda            #102
          sta            $06E3
          lda            #46
          sta            $06E4
          lda            #102
          sta            $06E5
          lda            #102
          sta            $06E6
          lda            #46
          sta            $06E7
          lda            #102
          sta            $06E8
          lda            #102
          sta            $06E9
          lda            #102
          sta            $06EA
          lda            #102
          sta            $06F8
          lda            #102
          sta            $06F9
          lda            #102
          sta            $06FA
          lda            #46
          sta            $06FB
          lda            #102
          sta            $06FC
          lda            #102
          sta            $06FD
          lda            #46
          sta            $06FE
          lda            #102
          sta            $06FF
          lda            #102
          sta            $0700
          lda            #46
          sta            $0701
          lda            #102
          sta            $0702
          lda            #102
          sta            $0703
          lda            #102
          sta            $0704
          lda            #102
          sta            $0705
          lda            #102
          sta            $0706
          lda            #102
          sta            $0707
          lda            #102
          sta            $0708
          lda            #46
          sta            $0709
          lda            #102
          sta            $070A
          lda            #102
          sta            $070B
          lda            #46
          sta            $070C
          lda            #102
          sta            $070D
          lda            #102
          sta            $070E
          lda            #46
          sta            $070F
          lda            #102
          sta            $0710
          lda            #102
          sta            $0711
          lda            #102
          sta            $0712
          lda            #102
          sta            $0720
          lda            #46
          sta            $0721
          lda            #46
          sta            $0722
          lda            #46
          sta            $0723
          lda            #46
          sta            $0724
          lda            #46
          sta            $0725
          lda            #46
          sta            $0726
          lda            #102
          sta            $0727
          lda            #102
          sta            $0728
          lda            #46
          sta            $0729
          lda            #46
          sta            $072A
          lda            #46
          sta            $072B
          lda            #46
          sta            $072C
          lda            #102
          sta            $072D
          lda            #46
          sta            $072E
          lda            #46
          sta            $072F
          lda            #46
          sta            $0730
          lda            #46
          sta            $0731
          lda            #102
          sta            $0732
          lda            #102
          sta            $0733
          lda            #46
          sta            $0734
          lda            #46
          sta            $0735
          lda            #46
          sta            $0736
          lda            #46
          sta            $0737
          lda            #46
          sta            $0738
          lda            #46
          sta            $0739
          lda            #102
          sta            $073A
          lda            #102
          sta            $0748
          lda            #46
          sta            $0749
          lda            #102
          sta            $074A
          lda            #102
          sta            $074B
          lda            #102
          sta            $074C
          lda            #102
          sta            $074D
          lda            #102
          sta            $074E
          lda            #102
          sta            $074F
          lda            #102
          sta            $0750
          lda            #102
          sta            $0751
          lda            #102
          sta            $0752
          lda            #102
          sta            $0753
          lda            #46
          sta            $0754
          lda            #102
          sta            $0755
          lda            #46
          sta            $0756
          lda            #102
          sta            $0757
          lda            #102
          sta            $0758
          lda            #102
          sta            $0759
          lda            #102
          sta            $075A
          lda            #102
          sta            $075B
          lda            #102
          sta            $075C
          lda            #102
          sta            $075D
          lda            #102
          sta            $075E
          lda            #102
          sta            $075F
          lda            #102
          sta            $0760
          lda            #46
          sta            $0761
          lda            #102
          sta            $0762
          lda            #102
          sta            $0770
          lda            #46
          sta            $0771
          lda            #102
          sta            $0772
          lda            #102
          sta            $0773
          lda            #102
          sta            $0774
          lda            #102
          sta            $0775
          lda            #102
          sta            $0776
          lda            #102
          sta            $0777
          lda            #102
          sta            $0778
          lda            #102
          sta            $0779
          lda            #102
          sta            $077A
          lda            #102
          sta            $077B
          lda            #46
          sta            $077C
          lda            #102
          sta            $077D
          lda            #46
          sta            $077E
          lda            #102
          sta            $077F
          lda            #102
          sta            $0780
          lda            #102
          sta            $0781
          lda            #102
          sta            $0782
          lda            #102
          sta            $0783
          lda            #102
          sta            $0784
          lda            #102
          sta            $0785
          lda            #102
          sta            $0786
          lda            #102
          sta            $0787
          lda            #102
          sta            $0788
          lda            #46
          sta            $0789
          lda            #102
          sta            $078A
          lda            #102
          sta            $0798
          lda            #46
          sta            $0799
          lda            #46
          sta            $079A
          lda            #46
          sta            $079B
          lda            #46
          sta            $079C
          lda            #46
          sta            $079D
          lda            #46
          sta            $079E
          lda            #46
          sta            $079F
          lda            #46
          sta            $07A0
          lda            #46
          sta            $07A1
          lda            #46
          sta            $07A2
          lda            #46
          sta            $07A3
          lda            #46
          sta            $07A4
          lda            #46
          sta            $07A5
          lda            #46
          sta            $07A6
          lda            #46
          sta            $07A7
          lda            #46
          sta            $07A8
          lda            #46
          sta            $07A9
          lda            #46
          sta            $07AA
          lda            #46
          sta            $07AB
          lda            #46
          sta            $07AC
          lda            #46
          sta            $07AD
          lda            #46
          sta            $07AE
          lda            #46
          sta            $07AF
          lda            #46
          sta            $07B0
          lda            #46
          sta            $07B1
          lda            #102
          sta            $07B2
          lda            #102
          sta            $07C0
          lda            #102
          sta            $07C1
          lda            #102
          sta            $07C2
          lda            #102
          sta            $07C3
          lda            #102
          sta            $07C4
          lda            #102
          sta            $07C5
          lda            #102
          sta            $07C6
          lda            #102
          sta            $07C7
          lda            #102
          sta            $07C8
          lda            #102
          sta            $07C9
          lda            #102
          sta            $07CA
          lda            #102
          sta            $07CB
          lda            #102
          sta            $07CC
          lda            #102
          sta            $07CD
          lda            #102
          sta            $07CE
          lda            #102
          sta            $07CF
          lda            #102
          sta            $07D0
          lda            #102
          sta            $07D1
          lda            #102
          sta            $07D2
          lda            #102
          sta            $07D3
          lda            #102
          sta            $07D4
          lda            #102
          sta            $07D5
          lda            #102
          sta            $07D6
          lda            #102
          sta            $07D7
          lda            #102
          sta            $07D8
          lda            #102
          sta            $07D9
          lda            #102
          sta            $07DA
          rts
;======================================================== 
ScreenRowTableDataL 
    byte $00 
    byte $28 
    byte $50 
    byte $78 
    byte $a0 
    byte $c8 
    byte $f0 
;------------------------------------------------------- 
    byte $18 
    byte $40 
    byte $68 
    byte $90 
    byte $b8 
    byte $e0 
;------------------------------------------------------- 
    byte $08 
    byte $30 
    byte $58 
    byte $80 
    byte $a8 
    byte $d0 
    byte $f8 
;-------------------------------------------------------- 
    byte $20 
    byte $48 
    byte $70 
    byte $98 
    byte $c0 
;======================================================== 
ScreenRowTableDataH
    byte $04 
    byte $04 
    byte $04 
    byte $04 
    byte $04 
    byte $04 
    byte $04 
;--------------------------------------------------------- 
    byte $05 
    byte $05 
    byte $05 
    byte $05 
    byte $05 
    byte $05 
;---------------------------------------------------------- 
    byte $06 
    byte $06 
    byte $06 
    byte $06 
    byte $06 
    byte $06 
    byte $06 
;---------------------------------------------------------- 
    byte $07 
    byte $07 
    byte $07 
    byte $07 
    byte $07 